# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Facultate/AdunareScadereVM/AdunareScadereVM.cache/wt [current_project]
set_property parent.project_path D:/Facultate/AdunareScadereVM/AdunareScadereVM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo d:/Facultate/AdunareScadereVM/AdunareScadereVM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/Decoder.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/Inc_Dec.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/comp2.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/ALU1.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/Round_Unit.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/shift_LR.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/controlUnit.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/aluMantisa.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/shiftUnit.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/kpd.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/displ7seg.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/debounce.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/addSubModule.vhd
  D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/sources_1/new/topModule.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/constrs_1/imports/AdunareScadereVM/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Facultate/AdunareScadereVM/AdunareScadereVM.srcs/constrs_1/imports/AdunareScadereVM/Nexys4DDR_Master.xdc]


synth_design -top topModule -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction one_hot


write_checkpoint -force -noxdef topModule.dcp

catch { report_utilization -file topModule_utilization_synth.rpt -pb topModule_utilization_synth.pb }
